apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-message
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-message
  template:
    metadata:
      labels:
        app: microservice-message
    spec:
      containers:
      - name: microservice-message
        image: rajpalsinghd/test:7024d5af7dcd63d0bfb78e8b6241ca3d974c5c36
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: logs
          mountPath: /home/ubuntu/microservice
      volumes: 
      - name: logs 
        hostPath: 
          path: /opt/apps/logs 
          type: DirectoryOrCreate        
---

apiVersion: v1
kind: Service
metadata:
  name: microservice-message-svc
 
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: microservice-message
  type: NodePort
