apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- ingress.yaml
- preview-service.yaml
images:
- name: rajpalsinghd/test
  newTag: 1272c28692c54be1a579942bf51722294963d953
